### ISSUE TITLE
Show the field key if no label is specified

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#129]
If the developer doesn't specify a label, we should show the field key in place.

This schema...

```
  - key: header
    type: group
    label: Header
    fields:
    - key: header.eyebrow
      type: text
    - key: header.headline
      type: text
    - key: header.body
      type: text
```

.. creates this set of fields:

![image](https://user-images.githubusercontent.com/646525/126723693-25c4c210-3c21-4711-a205-17daa8385773.png)
