### ISSUE TITLE
Use key as label if label not defined?

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#232]
This schema:

```
    - key: color
      type: radio
      label: Background color
      options:
      - value: blue
      - value: green
      - value: yellow
```

Produces this UI:

![image](https://user-images.githubusercontent.com/646525/129392994-4ac084fc-5f46-4225-8cc8-e502f44257ed.png)

Should we have it implicitly use `value` as the label?
